config/routes.rb
Kharcha::Application.routes.draw do

  resources :friends

  resources :authentications
	
	match '/auth/:provider/callback' => 'authentications#create'

	root :to => "expenditures#index"
	resources :expenditures
	resources :category
	devise_for :users, :controllers => {:registrations => 'registrations'}

		

end

app/models/friend.rb
class Friend < ActiveRecord::Base
	belongs_to :user
	
	has_many :expenditure
	
	validates_presence_of :name, :email
	validates :email , :presence => true , :uniqueness => true
	
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
  	 	@friends = current_user.friend.where("name like ?", "%#{params[:q]}%")
		respond_to do |format|
		  format.html
		  format.json { render :json => @friends.map(&:attributes) }
		  # format.json { render :json => @category.map(&:attributes) }
		end
  end

  def show
    @friend = Friend.find(params[:id])
  end

  def new
    @friend = current_user.friend.new
	respond_to do |format|
      format.html 
      format.js
    end
  end

  def create
    @friend = current_user.friend.new(params[:friend])
    respond_to do |format|
      if @friend.save
		@friends = current_user.friend.all
		@expenditures = current_user.expenditure.order("date DESC")
		format.html { redirect_to(@friends, :notice => 'Friend created.') }
        format.js
    else
        format.html { render :action => "new" }
        format.js  
    end
  end
	
  end

  def edit
    @friend = Friend.find(params[:id])
  end

  def update
    @friend = Friend.find(params[:id])
    if @friend.update_attributes(params[:friend])
      redirect_to @friend, :notice  => "Successfully updated friend."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy
    redirect_to friends_url, :notice => "Successfully destroyed friend."
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= simple_form_for(@friend) do |f| %>
		<%= f.input :name %>
		<%= f.input :email %>
		<%= f.input :thumb, :hint => "user image"%>
		<%= f.button :submit, "save" %>
<% end %>

app/views/friends/_friend.html.erb
<div class="authentication" style='border-top: 1px solid #BBC6D8;border-bottom: 1px solid #BBC6D8;width:98%;background: #FAFAFA repeat-x scroll 0 0;'>
			<%= image_tag("def3.jpg",:size => "32x32") %>
			<div class="provider">
				<%= friend.name %> 
			</div>
          <div class="uid">
				<%= friend.email %>
		  </div>
          <%= link_to "C", friend, :title =>'see friend details' , :class => "remove" %>
          <%= link_to "X", friend, :title =>'delete friend' ,:confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
</div>
<br/>

app/views/friends/create.js.erb
<% if @friend.save %>
	$(document).trigger('close.facebox')
	$("#friendBox").html("<%= escape_javascript(render(:partial => @friends)).html_safe %>");
<% else %>
	$.facebox('<%= escape_javascript(render :template => 'friends/new.html') %>');
	$('#facebox form').data('remote','true');
	$('#facebox .content p:last').remove();
<% end %>

app/views/friends/edit.html.erb
<% title "Edit Friend" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @friend %> |
  <%= link_to "View All", friends_path %>
</p>

app/views/friends/index.html.erb
<% title "Friends" %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Thumb</th>
    <th>User</th>
  </tr>
  <% for friend in @friends %>
    <tr>
      <td><%= friend.name %></td>
      <td><%= friend.email %></td>
      <td><%= friend.thumb %></td>
      <td><%= friend.user_id %></td>
      <td><%= link_to "Show", friend %></td>
      <td><%= link_to "Edit", edit_friend_path(friend) %></td>
      <td><%= link_to "Destroy", friend, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Friend", new_friend_path %></p>

app/views/friends/new.html.erb
<% title "New Friend" %>

<%= render 'form' %>

<p><%= link_to "Back to List", friends_path %></p>

app/views/friends/new.js.erb
$.facebox('<%= escape_javascript(render :template => 'friends/new.html') %>')
$('#facebox form').data('remote','true');
$('#facebox .content p:last').remove();

app/views/friends/show.html.erb
<% title "Friend" %>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>
<p>
  <strong>Thumb:</strong>
  <%= @friend.thumb %>
</p>
<p>
  <strong>User:</strong>
  <%= @friend.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_friend_path(@friend) %> |
  <%= link_to "Destroy", @friend, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", friends_path %>
</p>