config/routes.rb
Kharcha::Application.routes.draw do

  resources :friends

  resources :authentications
	
	match '/auth/:provider/callback' => 'authentications#create'

	root :to => "expenditures#index"
	resources :expenditures
	resources :category
	devise_for :users, :controllers => {:registrations => 'registrations'}

		

end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
	validates :amount, :numericality => true, :presence => {:message => "can't be blank"}
	validates_presence_of :date
	validates_presence_of :desc
	
	belongs_to :user
	belongs_to :friend
	has_and_belongs_to_many :category
	
	attr_reader :cat_tokens , :dir
	def cat_tokens=(ids)
		self.category_ids = ids.split(",")
	end
	def dir=( val )
		if(val)
		end
	end
	
	def setDefaultVal(name,dir)
		self.spender_name = name!="" ? name:"me"
		if(dir==0)
			if(self.amount>0)#make it negative if +ve
				self.amount = (-1)*(self.amount)
			end
		end
		if(dir==1)
			if(self.amount<0)#make it +ve if -ve
				self.amount = (-1)*(self.amount)
			end
		end
		# self.spender_id = id ? id : current_user.id
		# self.desc = desc!="" ? desc : "-NA-"
	end

end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  # can_edit_on_the_spot
  
  # GET /expenditures
  # GET /expenditures.json
  # before_filter :check_authorization
  before_filter :authenticate_user!
  def index
    # @expenditures = expenditure.order("date DESC")
    @expenditures = current_user.expenditure.order("date DESC")
    # @expenditure = current_user.expenditure.new
	@thumb = current_user.current_thumb(session[:currauth]);
    @friends = current_user.friend.all
	@total = @expenditures.sum('amount')
	# @spenders = current_user.expenditure.group(:spender_name).sum(:amount)
	# @category = current_user.expenditure.includes(:category).group("categories.cat_name").sum(:amount);

    # @category = Category.select('DISTINCT cat_name')

	respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @expenditures }
    end
  end

  # GET /expenditures/1
  # GET /expenditures/1.json
  def show
    @expenditure = current_user.expenditure.find(params[:id])
	respond_to do |format|
	  format.html # show.html.erb
	  format.json  { render :json => @expenditure }
	end
  end

  # GET /expenditures/new
  # GET /expenditures/new.json
  def new
    @expenditure = current_user.expenditure.new
    @friends = current_user.friend.all
    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /expenditures/1/edit
  def edit
    @expenditure = Expenditure.find(params[:id])
    @friends = current_user.friend.all
  end

  # POST /expenditures
  # POST /expenditures.json
  def create
	@target = params[:expenditure][:spender_name]!="" ? params[:expenditure][:spender_name] : "me";
	if(@target == "me")
		@expenditure = current_user.expenditure.new(params[:expenditure])
		@expenditure.user_id = current_user.id
		@expenditure.setDefaultVal(params[:expenditure][:spender_name],params[:expenditure][:dir])
		respond_to do |format|
		  if @expenditure.save
			@expenditures = current_user.expenditure.order("date DESC")
			@total = current_user.expenditure.sum('amount')
			format.html { redirect_to(@expenditure, :notice => 'Expenditure was successfully created.') }
			format.js
			# respond_with(@expenditure)
		  else
			format.html { render :action => "new" }
			format.js
		  end
		end
	else
		@friend = current_user.friend.find(@target);
		@expenditure = @friend.expenditure.new(params[:expenditure])
		@expenditure.setDefaultVal(params[:expenditure][:spender_name],params[:expenditure][:dir])
		respond_to do |format|
		  if @expenditure.save
			@expenditures = @friend.expenditure.order("date DESC")
			@total = @friend.expenditure.sum('amount')
			format.html { redirect_to(@expenditure, :notice => 'Expenditure was successfully created.') }
			format.js
			# respond_with(@expenditure)
		  else
			format.html { render :action => "new" }
			format.js
		  end
		end
		# render :text => @target.to_yaml
	end
  end

  # PUT /expenditures/1
  # PUT /expenditures/1.json
  def update
    @target = params[:expenditure][:spender_name]!="" ? params[:expenditure][:spender_name] : "me";
	if(@target == "me")
		@expenditure = current_user.expenditure.find(params[:id])
		@expenditure.user_id = current_user.id
		@expenditure.setDefaultVal(params[:expenditure][:spender_name],params[:expenditure][:dir])
		respond_to do |format|
		  if @expenditure.update_attributes(params[:expenditure])
			@expenditures = current_user.expenditure.order("date DESC")
			@total = current_user.expenditure.sum('amount')
			format.html { redirect_to(@expenditure, :notice => 'Expenditure was successfully created.') }
			format.js
			# respond_with(@expenditure)
		  else
			format.html { render :action => "new" }
			format.js
		  end
		end
	else
		@friend = current_user.friend.find(@target);
		@expenditure = @friend.expenditure.find(params[:id])
		@expenditure.setDefaultVal(params[:expenditure][:spender_name],params[:expenditure][:dir])
		respond_to do |format|
		  if @expenditure.update_attributes(params[:expenditure])
			@expenditures = @friend.expenditure.order("date DESC")
			@total = @friend.expenditure.sum('amount')
			format.html { redirect_to(@expenditure, :notice => 'Expenditure was successfully created.') }
			format.js
			# respond_with(@expenditure)
		  else
			format.html { render :action => "new" }
			format.js
		  end
		end
		# render :text => @target.to_yaml
	end
end

  # DELETE /expenditures/1
  # DELETE /expenditures/1.json
  def destroy

    @target = params[:spender_id]
	@expenditure = Expenditure.find(params[:id])
	@expenditure.destroy
	if(@target == "me")
		# @expenditure = current_user.expenditure.find(params[:id])
		# @expenditure.destroy
		@total = current_user.expenditure.sum('amount')
		@expenditures = current_user.expenditure.order("date DESC")

		respond_to do |format|
		  format.html { redirect_to(@expenditure) }
		  format.js
		end
	else
		# @expenditure = @friend.expenditure.find(params[:id])
		# @expenditure.destroy
		@friend = current_user.friend.find(@target);
		@expenditures = @friend.expenditure.order("date DESC")
		@total = @friend.expenditure.sum('amount')
		respond_to do |format|
			format.html { redirect_to(@expenditure, :notice => 'Expenditure was successfully destroyed.') }
			format.js
		  end
		# render :text => @target.to_yaml
	end
  end

	def calculateTotal
		total = current_user.expenditure.sum('amount')
		return total
	end
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/views/expenditures/_category.html.erb
<%= category.cat_name %>&nbsp;<br>

app/views/expenditures/_categorySummary.html.erb
<strong><%= categorySummary %></strong>&nbsp; 

app/views/expenditures/_expenditure.html.erb
<div class="expblock" id=<%= expenditure.id %>>
	<div class="exp_options">
		
	</div>
	<div class="exp_img">
	</div>
	<% if ( expenditure.amount < 0 ) %>  
		<div class="exp_amount" style='color:red;'>
			<%= expenditure.amount %>
		</div>
	<% else %>  
		<div class="exp_amount" style='color:green;'>
			<%= expenditure.amount %>
		</div>
	<% end %> 
	<div class="exp_desc">
		<%= expenditure.desc %>
	</div>
	<div class="exp_date">
		<%= expenditure.date %>
	</div>
	<div class="exp_date">
		<%= render :partial => 'category', :collection => expenditure.category %>
	</div>
	<div style='float:right;margin-right:20px;line-height:22px;'>
			<%= link_to image_tag("edit.png",:size => "12x12", :title => "edit expenditure"), {:action => "edit", :id => expenditure.id }, :remote=>true , :class=>'edit_post'%>
		<%= link_to image_tag("icon_close_remove.png",:size => "12x12", :title => "delete expenditure"),   {:action => "destroy", :id => expenditure.id ,:spender_id => id}, :confirm => 'Are you sure?', :remote=>true , :method => :delete ,:class=>'delete_post'%></td>
	</div>
</div>

app/views/expenditures/_expenditureBlock.html.erb
<div class='expenditureBlock'>
		<div class="expblockHead">
			<div class='logo'>
				<div class='user' style='margin:1px;float:left;'>
					<%= image_tag("arrow.png") %>
				</div>
					<%= title %>
			</div>
		</div>
			
		<div id='<%= id %>expenditureAll'>
			<%= render :partial => 'expenditures', :locals => { :id => id ,:data => dataObj , :total => totalVal } %>
		</div>
</div>

app/views/expenditures/_form.html.erb
<%= simple_form_for(@expenditure) do |f| %>
		<div id="form">
		<div class="alignLayout">
		<%= f.input :amount, :placeholder => "100, 300, 499" ,:input_html => { :maxlength => 15 ,:class => 'textInputs',:style => 'width:70px;'} %>
		<%= f.input :date, :as => :date_picker ,:placeholder => "date of expenditure",:input_html => { :maxlength => 55 ,:class => 'textInputs',:style => 'width:100px;'}%>
		<%= f.input :desc, :placeholder => "beer at hops, food from dhaba" ,:input_html => { :maxlength => 55 ,:class => 'textInputs',:style => 'width:300px;'}%>
		<%= f.input :cat_tokens, :label => "Category" , :input_html => { :class => 'textInputs' ,:style => 'float:left;width:120px;' , "data-pre"  => @expenditure.category.collect{|author| {:id => author.id, :name => author.cat_name}}.to_json } %>
		<div class='borderLayout'>
			<div class='inputs' style="float:left;color: #555555;display: block;font-weight: 700;margin-top: 8px">
				<input type="checkbox" name="friends" value="friends" />Friends
			</div>
			<%= f.input :dir, :label => "to/from" , :input_html => { :class => 'textInputs' ,:style => 'width:100px;'}, :collection => [[ "took from",0] , ["gave to",1] ], :prompt => "-NA-" %>
			<%= f.input :spender_name, :label => "Spender" , :input_html => { :class => 'textInputs' ,:style => 'width:120px;'},  :collection => @friends.collect{|q|[q.name,q.id]} , :prompt => "-NA-" %>
			<%= f.button :submit, "" , :class => 'inputButton'%>
		</div>
	</div>
	</div>
<% end %>

app/views/expenditures/_friend.html.erb
<strong><%= friend.name %></strong>&nbsp; 

app/views/expenditures/_total.html.erb
<span style='float:left;margin-left:2px;'>
	TOTAL:
</span>
<% if ( total < 0 ) %>  
		<span id='totalexp' class='totalexp' style='color:red;'>
			<%= total %>
		</span>
	<% else %>  
		<span id='totalexp' class='totalexp' style='color:green;'>
			<%= total %>
		</span>
	<% end %>
</span>

app/views/expenditures/create.js.erb
<% if @expenditure.save %>
	$("#actionData").html("");
  //$(document).trigger('close.facebox')
	$("#<%= @target %>totalBox").html("<%= escape_javascript(render(:partial => 'total' , :locals => { :total => @total })).html_safe %>");
	<% if @expenditures.length != 1 %>
		if($("#<%= @target %>expTable").find('div.expblock').length != 0){
			$("#<%= @target %>expTable").find('div.expblock').first().before('<%= escape_javascript(render( :partial =>  @expenditure , :locals => { :id =>  @target })).html_safe %>');
		}
		else{
			$("#<%= @target %>expTable").append('<%= escape_javascript(render( :partial =>  @expenditure , :locals => { :id =>  @target })).html_safe %>');
		}
	<% else %>
	<% end %>
	$("#<%= @target %>expenditureAll").html("<%= escape_javascript(render(:partial => 'expenditures', :locals => { :id => @target, :data => @expenditures , :total => @total })).html_safe %>");
<% else %>
	$("#actionData").html("<%= escape_javascript(render :template => 'expenditures/new.html') %>");
	$("#actionData").css('display','block');
	$('#actionData form').data('remote','true');
	//$.facebox('<%= escape_javascript(render :template => 'expenditures/new.html') %>')
	//$('#facebox form').data('remote','true');
	//$('#facebox .content p:last').remove();
<% end %>

app/views/expenditures/destroy.js.erb
$("#<%= @target %>totalBox").html("<%= escape_javascript(render(:partial => 'total' , :locals => { :total => @total })).html_safe %>");
<% if @expenditures.length == 0 %>
$("#<%= @target %>expenditureAll").html("<%= escape_javascript(render(:partial => 'expenditures', :locals => { :id => @target, :data => @expenditures , :total => @total })).html_safe %>");
<% end %>

app/views/expenditures/edit.html.erb
<h3>Edit expenditure</h3>
<%= render 'form' %>

app/views/expenditures/edit.js.erb
if($("#actionData").css('display')=='block'){
	$("#actionData").css('display','none');
	$("#actionData").html("");
}
$.facebox('<%= escape_javascript(render :template => 'expenditures/edit.html') %>')
$('#facebox form').data('remote','true');
$('#facebox .content p:last').remove();
$('#expenditure_cat_tokens').tokenInput('/category.json', { 
	crossDomain: false,
	hintText: 'press # and select a category  e.g. #food,#fuel...',
	prePopulate: $(this).data('pre'),
	theme: 'facebook'
});

$("input.date_picker").datepicker( {dateFormat:'M d, yy'});

app/views/expenditures/index.html.erb
<div class="actionBox">
				<%= link_to image_tag("add1.jpg",:size => "15x15",:title => "Add new Expenditure") + ' New Expense', {:action => "new" } , :remote => true %>
				<%= link_to image_tag("add_green_button.png",:size => "15x15",:title => "add friend") + " Add Friend" , { :action => "new", :controller=>"friends"}, :remote=>true %>
				<%= link_to image_tag("arrow.png",:size => "15x15",:title => "view notifications") + " Notifications(5)" , { :action => "new", :controller=>"friends"}, :remote=>true %>
<div id='actionData'>

</div>
</div>
<%= render :partial => 'expenditureBlock' , :locals => { :id => 'me', :title => "My Expense' Summary" , :totalVal => @total, :dataObj => @expenditures} %>
<% if @friends %>
	<% for friend in @friends %>
		<br/>
		<%= render :partial => 'expenditureBlock' , :locals => { :id =>  friend.id , :title => friend.name , :totalVal => friend.expenditure.sum('amount') , :dataObj => friend.expenditure.order("date DESC")} %>
	<% end %>
<% end %>

<div id="containerR">

		<div class='blocks'>
			<% if @friends.length!=0 %>
				<div class='user' style='width:100%;font-size:17px;line-height:17px;float:left;'>
				Friends
				</div>
			<div id='friendBox'>
				<%= render :partial => @friends %>
			</div>
			&nbsp;
			<% else %>
				
			<div class='user' style='line-height:17px;float:left;'>
				You have not added any friends yet!!!
				add friend with whom you share your expenses in daily needs 
				using below links
				<hr/>
			</div>
			<% end %>
			<div class="actionBox">
				<%= link_to image_tag("add1.jpg",:size => "15x15",:title => "add friend") + "add friend" , { :action => "new", :controller=>"friends"}, :remote=>true %>
			</div>
		</div>
	<div class="blocks user" style='display:none;'>
		<strong>TODO for </strong>
		alt:<a href='http://bit.ly/rczXEQ'>http://bit.ly/rczXEQ</a>
		<hr/>
		<ul>
		<li>DONE:total expenditure to be update with delete, add, update</li>
		<li>DONE:#category #food #fuel #movie #phone #shopping  </li>
		<li>DONE:multiple login</li>
		<li>DONE:@friend model</li>
		<li>@friend list import from fb tw.</li>
		<li>summary for @friend</li>
		<li>summary for #category</li>
		<li>send/share details to friends // advanced</li>
		<li>custom #category recurring monthly/daily/weekly</li>
		<li>group by month, pagination, data sorting  filtering criteria's</li>
		</ul>
		<%= link_to "Add Friends" , { :action => "new", :controller=>"friends"}, :remote=>true %>
	</div>
</div>

app/views/expenditures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @expenditure.amount %>
</p>

<p>
  <b>Desc:</b>
  <%= @expenditure.desc %>
</p>

<p>
  <b>Date:</b>
  <%= @expenditure.date %>
</p>

<p>
  <b>State:</b>
  <%= @expenditure.state %>
</p>


<%= link_to 'Edit', edit_expenditure_path(@expenditure) %> |
<%= link_to 'Back', expenditures_path %>

app/views/expenditures/update.js.erb
<% if @expenditure.save %>
	$(document).trigger('close.facebox');
	$("#<%= @target %>totalBox").html("<%= escape_javascript(render(:partial => 'total' , :locals => { :total => @total })).html_safe %>");
	$("#<%= @target %>expenditureAll").html("<%= escape_javascript(render(:partial => 'expenditures', :locals => { :id => @target, :data => @expenditures , :total => @total })).html_safe %>");

<% else %>
	$.facebox('<%= escape_javascript(render :template => 'expenditures/edit.html') %>')
  $('#facebox form').data('remote','true');
  $('#facebox .content p:last').remove();
<% end %>